// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :exec
INSERT INTO appointments (date_time, car_name, status, user_id, service_type) VALUES ($1, $2, $3, $4, $5)
`

type CreateAppointmentParams struct {
	DateTime    pgtype.Timestamptz
	CarName     pgtype.Text
	Status      NullAppointmentStatus
	UserID      pgtype.Int4
	ServiceType NullServiceType
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) error {
	_, err := q.db.Exec(ctx, createAppointment,
		arg.DateTime,
		arg.CarName,
		arg.Status,
		arg.UserID,
		arg.ServiceType,
	)
	return err
}

const getAllAppointments = `-- name: GetAllAppointments :many
SELECT id, date_time, car_name, status, user_id, created_at, updated_at, service_type FROM appointments
`

func (q *Queries) GetAllAppointments(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAllAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.DateTime,
			&i.CarName,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, date_time, car_name, status, user_id, created_at, updated_at, service_type FROM appointments where id = $1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id int32) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DateTime,
		&i.CarName,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceType,
	)
	return i, err
}

const getAppointmentsByUserID = `-- name: GetAppointmentsByUserID :many
SELECT id, date_time, car_name, status, user_id, created_at, updated_at, service_type FROM appointments where user_id = $1
`

func (q *Queries) GetAppointmentsByUserID(ctx context.Context, userID pgtype.Int4) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.DateTime,
			&i.CarName,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
