// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppointmentStatus string

const (
	AppointmentStatusPending   AppointmentStatus = "pending"
	AppointmentStatusConfirmed AppointmentStatus = "confirmed"
	AppointmentStatusCompleted AppointmentStatus = "completed"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type ServiceType string

const (
	ServiceTypeWashing            ServiceType = "washing"
	ServiceTypeVacuuming          ServiceType = "vacuuming"
	ServiceTypeWashingAndVacuming ServiceType = "washing_and_vacuming"
	ServiceTypeDeepCleaning       ServiceType = "deep_cleaning"
)

func (e *ServiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceType(s)
	case string:
		*e = ServiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceType: %T", src)
	}
	return nil
}

type NullServiceType struct {
	ServiceType ServiceType
	Valid       bool // Valid is true if ServiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceType) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceType), nil
}

type Appointment struct {
	ID          int32
	DateTime    pgtype.Timestamptz
	CarName     pgtype.Text
	Status      NullAppointmentStatus
	UserID      pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ServiceType NullServiceType
}

type User struct {
	ID        int32
	Name      pgtype.Text
	LastName  pgtype.Text
	Email     pgtype.Text
	Password  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
